# Copyright 2021 lihuiguo
# See LICENSE file for licensing details.
#
# Learn more about config at: https://juju.is/docs/sdk/config

options:
  port:
    description: The port mariadb will be listening on
    type: int
    default: 3306